@server_HostAddress = https://localhost:5000
@userId = fredflintstone
@group = INS1
@userId = wilmaflintstone
@group = INS1

# @name login
GET {{server_HostAddress}}/message/jwt?userId={{userId}}&group={{group}}
Accept: application/json

@bearerToken= {{login.response.body.token}}

###
GET {{server_HostAddress}}/message?msg=This is a test at {{$datetime rfc1123}}
Authorization: Bearer {{bearerToken}}
Content-Type: application/json

###
GET {{server_HostAddress}}/message/send-to?userId={{userId}}&msg=This is a test at {{$datetime rfc1123}}
Authorization: Bearer {{bearerToken}}
Content-Type: application/json

### @name groupTest
GET {{server_HostAddress}}/message/send-to?userId=@INS1&msg=This is a group test at {{$datetime rfc1123}}
Authorization: Bearer {{bearerToken}}
Content-Type: application/json
