name: .NET Core

on:
  push:
    branches: [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/dotnet-core.yml'
  pull_request:
    branches: [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/dotnet-core.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-dotnet@v1
      name: Setup .NET Core
      with:
        dotnet-version: 9.0.x

    - name: Install dependencies
      run: dotnet restore
      working-directory: ./server

    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./server

    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: ./server
